// Code generated by SQLGen. DO NOT EDIT.
package examples

import (
	_ "embed"

	"github.com/abetd/gqlgen"
)

//go:embed select_items.sql
var selectItemsQueryElemSQL string

type SelectItemsQueryElem struct {
	ID                 int
	IsSelectMultiNames bool
	Where              string
	Sep                string
	Names              []interface{}
}

func (e *SelectItemsQueryElem) SQLTemplate() string {
	return selectItemsQueryElemSQL
}

func (e *SelectItemsQueryElem) Query() (*sqlgen.Query, error) {
	return sqlgen.CreateQuery(e)
}

//go:embed select_users.sql
var selectUsersQueryElemSQL string

type SelectUsersQueryElem struct {
	ID    int
	Name  string
	Names []interface{}
}

func (e *SelectUsersQueryElem) SQLTemplate() string {
	return selectUsersQueryElemSQL
}

func (e *SelectUsersQueryElem) Query() (*sqlgen.Query, error) {
	return sqlgen.CreateQuery(e)
}
